# -*- coding: utf-8 -*-
"""MissingNumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7O-KcD7OSCEeU50PAHeeNGNccqdleLi

Problem Statement : You are given a list of n-1 integers and these integers are in the range of 1 to n. There are no duplicates in the list. One of the integers is missing in the list. Write an efficient code to find the missing integer.
"""

# Method Definition
def getMissingNum(arr,n):
  totalsum = n*(n+1)//2
  return totalsum - sum(arr)

# Driver Code
arr = [1,2,4,5,6]
n = len(arr) + 1
getMissingNum(arr,n)

"""More Efficient Approach to Use : Using XOR"""

# Method Definition
def getMissingNumber(arr,n):
  a = arr[0]
  b = 1
  # XOR Operation on array elements
  for i in range(1,n):
    a = a ^ arr[i]
  
  # XOR Operation on given range of elements
  for i in range(2,n+2):
    b = b ^ i
  return a ^ b

# Driver Code
arr = [1,2,4,5,6]
n = len(arr)
getMissingNumber(arr,n)

