# -*- coding: utf-8 -*-
"""reverseArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlSxzSJ5JlW2ZG87wTT6Prt9kmtpC2U2
"""

#Method to define reverse in a array
def reverseArray(A,start,end):
  while start < end:
    # Swap an element in an array in Python
    A[start],A[end] = A[end],A[start]
    start = start + 1
    end = end - 1

#n -> Number of elements in an array
n = int(input("Size of an array"))
A = []
for i in range(n):
  element = int(input("Enter the element"))
  A.append(element)

print(A)
reverseArray(A,0,n-1)
print(A)

23